# Generated by Django 5.0.1 on 2026-03-12 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.campus'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_campus',
            field=models.ForeignKey(blank=True, help_text='Campus managed by curator/host', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curators', to='core.campus'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student/Alumni'), ('DROP_HOST', 'Drop Host'), ('CAMPUS_CURATOR', 'Campus Curator'), ('GLOBAL_ADMIN', 'Global Admin/Operations')], default='STUDENT', max_length=20),
        ),
    ]
